// config.bin - 22:47:26 01/04/14, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DK_units {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Characters_F_BLUFOR"};
	};
};

class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};

class CfgFactionClasses {
	class DK_units {
		displayName = "Denmark";
		priority = 3;//was 2
		side = 1;//was TWest
		icon = "\uniforms\data\cfgfaction_DK.paa";
		};
};

class CfgVehicleClasses {
	class DanishPletM90_units {
		displayName = "Infantry (M90-Sportcamo)";
	};
};

class CfgVehicles {
	class B_Soldier_base_F;	// External class reference
	
	class dkPletM90_Soldier_H : B_Soldier_base_F {
		_generalMacro = "B_Soldier_base_F";
		faction = "DK_Units";
		scope = public;
		displayName = "Danish M90 Pletcamo Soldier";
		nakedUniform = "U_BasicBody";
		uniformClass = "dkPletM90Uniform_H";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"Uniforms\Data\DanishPletM90\dkPletM90Cloth.paa"};
		linkedItems[] = {"dkPletM90_Helmet", "dkPletM90_PlateCarrier2", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"dkPletM90_Helmet", "dkPletM90_PlateCarrier2", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class dkPletM90_Soldier_TS : B_Soldier_base_F {
		_generalMacro = "B_Soldier_base_F";
		faction = "DK_Units";
		scope = public;
		displayName = "Danish M90 Pletcamo Soldier T-Shirt";
		model = "\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		nakedUniform = "U_BasicBody";
		uniformClass = "dkPletM90Uniform_H_TS";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"Uniforms\Data\DanishPletM90\dkPletM90Cloth.paa"};
		linkedItems[] = {"dkPletM90_Helmet", "dkPletM90_PlateCarrier2", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"dkPletM90_Helmet", "dkPletM90_PlateCarrier2", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class dkPletM90_Soldier_RS : B_Soldier_base_F {
		_generalMacro = "B_Soldier_base_F";
		faction = "DK_Units";
		scope = public;
		displayName = "Danish M90 Pletcamo Soldier Rolled Sleeves";
		model = "\A3\characters_F\BLUFOR\b_soldier_03.p3d";
		nakedUniform = "U_BasicBody";
		uniformClass = "dkPletM90Uniform_H_RS";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"Uniforms\Data\DanishPletM90\dkPletM90Cloth.paa"};
		linkedItems[] = {"dkPletM90_Helmet", "dkPletM90_PlateCarrier2", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"dkPletM90_Helmet", "dkPletM90_PlateCarrier2", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
};

class cfgWeapons {
	class Uniform_Base;	// External class reference
	class UniformItem;	// External class reference
	class Vest_NoCamo_Base;	// External class reference
	class VestItem;	// External class reference
	class HeadgearItem;	// External class reference
	class ItemCore;	// External class reference
	
	class dkPletM90Uniform_H : Uniform_Base {
		scope = public;
		displayName = "Danish M90 Pletcamo Uniform";
		picture = "\A3\characters_f\data\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "dkPletM90_Soldier_H";
			containerClass = "Supply40";
			mass = 80;
		};
	};
	
	class dkPletM90Uniform_H_TS : Uniform_Base {
		scope = public;
		displayName = "Danish M90 Pletcamo Uniform TS";
		picture = "\A3\characters_f\data\ui\icon_u_b_combatuniform_mcam_tshirt_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "dkPletM90_Soldier_TS";
			containerClass = "Supply40";
			mass = 80;
		};
	};
	
	class dkPletM90Uniform_H_RS : Uniform_Base {
		scope = public;
		displayName = "Danish M90 Pletcamo Uniform RS";
		picture = "\A3\characters_f\data\ui\icon_U_B_CombatUniform_mcam_vest_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "dkPletM90_Soldier_RS";
			containerClass = "Supply40";
			mass = 80;
		};
	};
	
	class dkPletM90_PlateCarrier1 : Vest_NoCamo_Base {
		scope = public;
		displayName = "Danish M90 Pletcamo Platecarrier";
		picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Uniforms\Data\DanishPletM90\dkPletM90Vests.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
			containerClass = "Supply120";
			mass = 50;
			armor = "5*0.5";
			passThrough = 0.7;
			hiddenSelections[] = {"camo"};
		};
	};
	
	class dkPletM90_PlateCarrier2 : Vest_NoCamo_Base {
		scope = public;
		displayName = "Danish M90 Pletcamo Platecarrier2";
		picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest01";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Uniforms\Data\DanishPletM90\dkPletM90Vests.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest01";
			containerClass = "Supply120";
			mass = 50;
			armor = "5*0.5";
			passThrough = 0.7;
			hiddenSelections[] = {"camo"};
		};
	};
	
	class dkPletM90_Helmet : ItemCore {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "Danish M90 Pletcamo Helmet";
		picture = "\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		model = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"Uniforms\Data\DanishPletM90\dkPletM90Equip.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\Characters_F\BLUFOR\headgear_b_helmet_ballistic";
			modelSides[] = {3, 1};
			armor = "3*0.5";
			passThrough = 0.8;
			hiddenSelections[] = {"camo"};
		};
	};
};
